# Generated by Django 3.0 on 2019-12-03 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=60, unique=True, verbose_name='phone')),
                ('name', models.CharField(default='name', max_length=60, verbose_name='name')),
                ('surname', models.CharField(default='surname', max_length=60, verbose_name='surname')),
                ('dob', models.DateField(default=datetime.date(1997, 10, 19), verbose_name='dob')),
                ('gender', models.CharField(default='N', max_length=1, verbose_name='gender')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
