# Generated by Django 2.1.1 on 2019-12-10 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=60, unique=True, verbose_name='phone')),
                ('name', models.CharField(default='name', max_length=60, verbose_name='name')),
                ('surname', models.CharField(default='surname', max_length=60, verbose_name='surname')),
                ('dob', models.DateField(default=datetime.date(1997, 10, 19), verbose_name='dob')),
                ('gender', models.CharField(default='N', max_length=1, verbose_name='gender')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 19, 41, 56, 127556), verbose_name='date_joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 19, 41, 56, 127600), verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('card_image', models.CharField(default='/card', max_length=60, verbose_name='card_image')),
                ('stamp_need', models.IntegerField(default=9, verbose_name='stamp_need')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('permission', models.BooleanField(default=False, verbose_name='permission')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60, verbose_name='token')),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.BusinessAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_number', models.IntegerField(default=0, verbose_name='stamp_number')),
                ('stamp_total', models.IntegerField(default=9, verbose_name='stamp_total')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
