# Generated by Django 2.1.1 on 2019-11-30 22:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.date(1997, 10, 19), verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='N', max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='name'),
            preserve_default=False,
        ),
    ]
