# Generated by Django 2.1.1 on 2019-11-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191130_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='name', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(default='surname', max_length=60, verbose_name='surname'),
        ),
    ]
