version: '3'

volumes:
  psqldbdata: {}

services:
  redis:
    build: ./compose/redis
    container_name: sample_redis
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: sample_django
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - DATABASE_NAME=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    tty: true
  