# Generated by Django 2.1.1 on 2019-10-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('express_id', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('catalog_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('catalog_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalogType')),
            ],
        ),
    ]
